name: DownLoad CSV

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      google_spreadsheet_id:
        description: 'Google Spreadsheet ID for the CEDAR Template'
        default: '1Kwe4PFodciXo-XDX2bHN8F-CRAmopguoI9YKFX6piaQ'
        required: false
      google_sheet_name:
        description: 'Google Sheet tab name for the CEDAR Template'
        required: true

jobs:
  cedar_integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Download Google Sheet as CSV
        run: |
          spreadsheet_id="${{ github.event.inputs.google_spreadsheet_id }}"
          sheet_name="${{ github.event.inputs.google_sheet_name }}"
          csv_url="https://docs.google.com/spreadsheets/d/${spreadsheet_id}/export?format=csv&gid=${sheet_name}"
          echo "Downloading CSV from: $csv_url"
          curl -L -o template.csv "$csv_url"
          echo "Downloaded CSV file content:"
          cat template.csv
